run:
	@g++ test.cpp ../src/dominio/historial.cpp ../src/dominio/navegador.cpp ../src/dominio/utilidades.cpp ../src/dominio/favoritos.cpp ../src/datos/manejadorHTML_.cpp ../src/datos/manejadorFicheros.cpp -o test
	@./test
	@rm test

